### ISSUE TITLE
Data panel does not work with 1.8.0-beta.4

### ISSUE THREAD

**Issue by iamolivinius** [emberjs/ember-inspector#236]
I created a very basic app in ember cli 0.1.1 and updated the ember version to 1.8.0-beta.4 afterwards. When i fire up the ember inspector and click the data panel the following error occures:

```
Uncaught TypeError: undefined is not a function vendor.js:49337(anonymous function) vendor.js:49337
Cache.get vendor.js:25071
underscore vendor.js:49404
(anonymous function) vendor.js:68316
cb vendor.js:29023
OrderedSet.forEach vendor.js:28815
Map.forEach vendor.js:29027
__exports__.default.Ember.DataAdapter.extend.columnsForType vendor.js:68314
apply vendor.js:32729
superWrapper vendor.js:32301
__exports__.default.EmberObject.extend.wrapModelType vendor.js:17652
(anonymous function) vendor.js:17467
__exports__.default.EmberObject.extend.watchModelTypes vendor.js:17465
Ember.Object.extend.messages.getModelTypes VM1431:514
apply vendor.js:32729
sendEvent vendor.js:27753
__exports__.default.Mixin.create.trigger vendor.js:44946
(anonymous function) VM1431:1843
(anonymous function) VM1431:200
Ember.Object.extend._messageReceived VM1431:199
(anonymous function) VM1431:284
Backburner.run vendor.js:13360
apply vendor.js:32729
run vendor.js:31284(anonymous function) VM1431:283
```

This error occures using a RESTAdapter as well as the FixtureAdapter. 

I'm using ember-inspector 1.5.0 for chrome.

Please let me know if you need further information and if you can approve this bug. Here you can find the code: https://github.com/iamolivinius/testapp
