### ISSUE TITLE
Using Inspector (3.12.2) to view a particular Component or Data Model record fails with the following error:

### ISSUE THREAD

**Issue by iofusion** [emberjs/ember-inspector#1068]
Ember                 : 3.11.1
Ember Data        : 3.11.4
Inspector            : 3.12.2
Chrome Version 80.0.3963.0 (Official Build) canary (64-bit)

Inspecting a Component, Data Model Record or Container results in:

Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: glimmer.value is not a function
Stack trace: TypeError: glimmer.value is not a function
    at <anonymous>:3551:42
    at Array.forEach (<anonymous>)
    at <anonymous>:3531:24
    at Array.forEach (<anonymous>)
    at calculateCPs (<anonymous>:3530:18)
    at Class.mixinsForObject (<anonymous>:3254:7)
    at Class.sendObject (<anonymous>:3068:26)
    at Class.inspectById (<anonymous>:2990:16)
    at sendEvent (http://localhost:4200/assets/vendor.js:30041:14)
    at Class.trigger (http://localhost:4200/assets/vendor.js:44727:28)

**Comment by chancancode** [comment]
This is introduced in #1035, @pzuraq @patricklx do you mind taking a look?

**Comment by rwwagner90** [comment]
@iofusion do you have an app we could reproduce this error on?

**Comment by rwwagner90** [comment]
This can be reproduced by clicking something in the data tab and trying to inspect it, as talked about in this duplicate issue https://github.com/emberjs/ember-inspector/issues/1071.

**Comment by patricklx** [comment]
Looks like we need one more check for glimmer.value
https://github.com/emberjs/ember-inspector/blob/8b977a6287a59e1c3cc1fd37ad706fd915bd9d37/ember_debug/object-inspector.js#L914
Though is it strange that there is metal.track but not glimmer?

**Comment by enspandi** [comment]
Same here - just appeared this morning with latest update.

**Comment by kumkanillam** [comment]
I am also getting the same error in the latest 3.12.2 version of the ember inspector. 
```
VM46:92 Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: glimmer.value is not a function
Stack trace: TypeError: glimmer.value is not a function
    at <anonymous>:3551:42
    at Array.forEach (<anonymous>)
    at <anonymous>:3531:24
    at Array.forEach (<anonymous>)
    at calculateCPs (<anonymous>:3530:18)
    at Class.mixinsForObject (<anonymous>:3254:7)
    at Class.sendObject (<anonymous>:3068:26)
    at Class.inspectById (<anonymous>:2990:16)
    at sendEvent (http://localhost/assets/vendor.js:36714:14)
    at Class.trigger (http://localhost/assets/vendor.js:51185:28)
```

**Comment by iofusion** [comment]
@kumkanillam #1072 fixes this issue, but that update was not available in the Chrome extension store last I checked.  There are instruction in this repo's [readMe](https://github.com/emberjs/ember-inspector) for installing manually.

**Comment by pjcarly** [comment]
There hasn't been a new release yet. So I guess that is normal
