### ISSUE TITLE
Can not build on current node (v8.9.0)

### ISSUE THREAD

**Issue by pichfl** [emberjs/ember-inspector#736]
Trying to build the project at b306318d9fdf7230a7f8911db220d8fb21d6f3ed results in this error:

```sh
npm run build:production

> ember-inspector@1.10.0 build:production /Users/pichfl/Repositories/ember-inspector
> ember build --environment production && grunt compress:main clean-tmp build-xpi

module.js:538
    throw err;
    ^

Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:31:26
    at Object.<anonymous> (/Users/pichfl/Repositories/ember-inspector/node_modules/ember-cli/node_modules/configstore/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ember-inspector@1.10.0 build:production: `ember build --environment production && grunt compress:main clean-tmp build-xpi`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ember-inspector@1.10.0 build:production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pichfl/.npm/_logs/2017-11-15T10_35_01_965Z-debug.log
```

**Comment by teddyzeenny** [comment]
Hi, can you please try using yarn for installing and building?

**Comment by pichfl** [comment]
Using Node 4 (yarn 1.3.2)

```sh
yarn --ignore-engines; and yarn run build:production
yarn install v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
✨  Done in 35.54s.
yarn run v1.3.2
$ ember build --environment production && grunt compress:main clean-tmp build-xpi
Future versions of Ember CLI will not support v4.8.6. Please update to Node 0.12 or io.js.
version: 0.2.0

A new version of ember-cli is available (2.16.2). To install it, type ember update.
invalid watchman found, version: [4.9.0] did not satisfy [^3.0.0], falling back to NodeWatcher
Build failed.
Path or pattern "vendor/ic-ajax/dist/named-amd/main.js" did not match any files
Error: Path or pattern "vendor/ic-ajax/dist/named-amd/main.js" did not match any files
    at Object.multiGlob (/Users/pichfl/Repositories/ember-inspector/node_modules/broccoli-kitchen-sink-helpers/index.js:204:13)
    at Class.module.exports.CachingWriter.extend._addFiles (/Users/pichfl/Repositories/ember-inspector/node_modules/broccoli-sourcemap-concat/simple-concat.js:82:13)
    at Class.module.exports.CachingWriter.extend.updateCache (/Users/pichfl/Repositories/ember-inspector/node_modules/broccoli-sourcemap-concat/simple-concat.js:50:12)
    at /Users/pichfl/Repositories/ember-inspector/node_modules/broccoli-caching-writer/index.js:92:34
    at tryCatch (/Users/pichfl/Repositories/ember-inspector/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/pichfl/Repositories/ember-inspector/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/Users/pichfl/Repositories/ember-inspector/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/Users/pichfl/Repositories/ember-inspector/node_modules/rsvp/dist/rsvp.js:2415:5)
    at nextTickCallbackWith0Args (node.js:489:9)
    at process._tickCallback (node.js:418:13)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Using node v6.12.0 (npm v3.10.10) (yarn 1.3.2)
```sh
❯ nvm use 6
Now using node v6.12.0 (npm v3.10.10)

~/Repositories/ember-inspector master*
❯ yarn --ignore-engines; and yarn run build:production
yarn install v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
✨  Done in 23.96s.
yarn run v1.3.2
$ ember build --environment production && grunt compress:main clean-tmp build-xpi
(node:6813) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:6813) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Future versions of Ember CLI will not support v6.12.0. Please update to Node 0.12 or io.js.
version: 0.2.0

A new version of ember-cli is available (2.16.2). To install it, type ember update.
invalid watchman found, version: [4.9.0] did not satisfy [^3.0.0], falling back to NodeWatcher
Build failed.
Path or pattern "vendor/ic-ajax/dist/named-amd/main.js" did not match any files
Error: Path or pattern "vendor/ic-ajax/dist/named-amd/main.js" did not match any files
    at Object.multiGlob (/Users/pichfl/Repositories/ember-inspector/node_modules/broccoli-kitchen-sink-helpers/index.js:204:13)
    at Class._addFiles (/Users/pichfl/Repositories/ember-inspector/node_modules/broccoli-sourcemap-concat/simple-concat.js:82:13)
    at Class.updateCache (/Users/pichfl/Repositories/ember-inspector/node_modules/broccoli-sourcemap-concat/simple-concat.js:50:12)
    at /Users/pichfl/Repositories/ember-inspector/node_modules/broccoli-caching-writer/index.js:92:34
    at tryCatch (/Users/pichfl/Repositories/ember-inspector/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/pichfl/Repositories/ember-inspector/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/Users/pichfl/Repositories/ember-inspector/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/Users/pichfl/Repositories/ember-inspector/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Using node v8.9.0 (npm v5.5.1) (yarn 1.3.2)
```sh
nvm use default
Now using node v8.9.0 (npm v5.5.1)

~/Repositories/ember-inspector master*
❯ which ember
/Users/pichfl/.nvm/versions/node/v8.9.0/bin/ember

~/Repositories/ember-inspector master*
❯ yarn --ignore-engines; and yarn run build:production
yarn install v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
✨  Done in 77.76s.
yarn run v1.3.2
$ ember build --environment production && grunt compress:main clean-tmp build-xpi
module.js:538
    throw err;
    ^

Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:31:26
    at Object.<anonymous> (/Users/pichfl/Repositories/ember-inspector/node_modules/ember-cli/node_modules/configstore/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by teddyzeenny** [comment]
This command doesn't exist in current master anymore (it was changed a few versions ago): `ember build --environment production && grunt compress:main clean-tmp build-xpi`. 

Are you sure you're building master and not an old commit?

[yarn run build:production](https://github.com/emberjs/ember-inspector/blob/825f3de9244b952f564789d9ba2241e912e51eb8/package.json#L14) is different on master.

**Comment by pichfl** [comment]
@teddyzeenny turns out I had two clones of the Inspector checked out and one was stuck on an ancient commit. (╯°□°）╯︵ ┻━┻  

Sorry for the trouble. I checked everything twice but did not realize that Tower points to a different directory than where I was building. 

Works now.

**Comment by teddyzeenny** [comment]
No worries! Glad it works now 🍻
