### ISSUE TITLE
3.3.0 Chrome Error opening model details

### ISSUE THREAD

**Issue by Fabschu** [emberjs/ember-inspector#854]
HI, 
since the update to 3.3.0 the following error is thrown opening a model detail in the data tab:

```
VM457:92 Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: this.eachAttribute is not a function
Stack trace: TypeError: this.eachAttribute is not a function
    at _debugInfo (http://localhost:4200/assets/vendor.js:324667:12)
    at getDebugInfo (<anonymous>:3359:19)
    at Class.mixinsForObject (<anonymous>:2993:23)
    at Class.sendObject (<anonymous>:2885:26)
    at Class.inspectModel (<anonymous>:721:37)
    at Object.sendEvent (http://localhost:4200/assets/vendor.js:34902:18)
    at Class.trigger (http://localhost:4200/assets/vendor.js:51049:19)
    at wrap (<anonymous>:3461:14)
    at Class.<anonymous> (<anonymous>:3491:18)
    at Backburner.run (http://localhost:4200/assets/vendor.js:17329:23)
    at run (http://localhost:4200/assets/vendor.js:39327:27)
    at Class.wrap (<anonymous>:3489:14)
    at Class.messageReceived (<anonymous>:3460:12)
    at get.onMessageReceived.message (<anonymous>:3454:16)
    at get.forEach.callback (<anonymous>:127:9)
    at Array.forEach (<anonymous>)
    at Class._messageReceived (<anonymous>:126:37)
    at run (<anonymous>:344:16)
    at Backburner.run (http://localhost:4200/assets/vendor.js:17329:23)
    at run (http://localhost:4200/assets/vendor.js:39327:27)
    at MessagePort.chromePort.addEventListener.event (<anonymous>:343:9)
  | warn | @ | VM457:92
-- | -- | -- | --
  | handleError | @ | VM457:149
  | (anonymous) | @ | VM457:3493
  | run | @ | ember.debug.js:707
  | run | @ | ember.debug.js:22705
  | wrap | @ | VM457:3489
  | messageReceived | @ | VM457:3460
  | get.onMessageReceived.message | @ | VM457:3454
  | get.forEach.callback | @ | VM457:127
  | _messageReceived | @ | VM457:126
  | run | @ | VM457:344
  | run | @ | ember.debug.js:707
  | run | @ | ember.debug.js:22705
  | chromePort.addEventListener.event | @ | VM457:343
```

We are using: 
DEBUG: Ember             : 2.12.2
DEBUG: Ember Data        : 2.12.2
DEBUG: jQuery            : 2.2.4
DEBUG: Ember Simple Auth : 1.1.0

**Comment by Ghostubborn** [comment]
+1

**Comment by rwwagner90** [comment]
Duplicate of https://github.com/emberjs/ember-inspector/issues/851. We're working on getting a release out today.
