### ISSUE TITLE
Ember inspector not loading: TypeError: window.requireModule.has is not a function

### ISSUE THREAD

**Issue by LordOfCorners** [emberjs/ember-inspector#2226]
**Describe the bug**
I have a site that is using pretty old versions of everything, but from what I understand the ember inspector should work with version 1.0 and above. (I am on 1.12.2). Not sure if it's a bug or if there's something wrong in my setup. I am getting the following error in the console.

`TypeError: window.requireModule.has is not a function`

**Expected behavior**
Inspector should load without errors

**Screenshots**
<img width="572" alt="image" src="https://user-images.githubusercontent.com/3781147/199838602-dec3ec2e-c310-4af3-8b7c-a20035ca65a5.png">

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/3781147/199838666-c71a8ce7-3870-4828-8c6a-7e2426fe6dd2.png">

<img width="633" alt="image" src="https://user-images.githubusercontent.com/3781147/199839489-88581c37-ff08-4e9d-9793-959e91c4980f.png">

**Environment**
<img width="204" alt="image" src="https://user-images.githubusercontent.com/3781147/199838717-4171d9ee-dca7-4492-934e-4f686ec55396.png">

Happens in both chrome and firefox

**Comment by LordOfCorners** [comment]
@patricklx thank you so much for addressing this so quickly 🙏 . It's not on the chrome store yet, but I tried downloading 4.9.1 and building it for production and loading into chrome manually (ember version was too old for development version) and the error was the same. It appeared to be using the old code? 4.9.1 appears to be on firefox already so I tried it there and ran into the same thing. Do you have any advice?

**Comment by patricklx** [comment]
Is it exactly the same error? what do you mean by loading it manually? You can download the build extension from here https://github.com/emberjs/ember-inspector/actions/runs/3395073172 at the bottom are the links. Then you need to load it into chrome as an extension and disable the other ember inspector. Then hard reload as it's probably still in the cache

**Comment by LordOfCorners** [comment]
Yeah it's the exact same error. By loading it manually I meant I built it and then loaded it into chrome via the "Load unpacked" button. On firefox though it's already hit their extensions page so I just used that one. 

Just tried the one from the link you shared. I have restarted chrome, done a hard refresh, removed old version, and it's still the exact same error. 

<img width="416" alt="image" src="https://user-images.githubusercontent.com/3781147/200064699-b9080cb5-271c-4a4f-bbbf-d869f63c6f42.png"> 
(the error there is just "Manifest version 2 is deprecated, and support will be removed in 2023")

**Comment by LordOfCorners** [comment]
Oh wait it finally started working for me. Thanks!

**Comment by LordOfCorners** [comment]
Ok so I have removed the old one, installed the download from your link, hard refreshed, pressed the reload extension icon on the extension page, and I am still getting the exact same error on Chrome no matter what. Weirdly, in firefox ([using the live 4.9.1 extension ](https://addons.mozilla.org/en-US/firefox/addon/ember-inspector/), it also gives same error but if I hold down command + r for a while it eventually loads. I realize that's not super helpful so I'll see if I can figure out any other details for you.
